spring:
  profiles:
    active: local   # local ?? ?? ??, prod : ?? (?? ?? ??)

  jpa:
    hibernate:
      ddl-auto: update   # ?? ??, ??? prod.yml??
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
