spring:
  profiles:
    active: local # local ?? ?? ??, prod : ?? (?? ?? ??)

  jpa:
    hibernate:
      ddl-auto: update # ?? ??, ??? prod.yml??
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

# 파일 업로드 설정
app:
  file:
    upload-dir: uploads/ownership
